server:
  port: 8081

jwt:
  secret: private
  lifetime: 30m

spring:
  data:
    mongodb:
      host: localhost
      port: 27017

  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: true

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgresTE!