spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ENC(V8dpiXTt/2c2Zuah+wJpm8AHKz1pPUqzM3dDTK1JcjjbW1HHPG6gVcv/lub9RU+W)

  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: create
#      hibernate.show_sql: true
      hibernate.format_sql: true

jasypt:
  encryptor:
    password: password



