spring:
  application:
    name: docker-database-server-provider

  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    open-in-view: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always

logging:
  level:
    root: error
  file:
    name: "./log"
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

custom:
  path: "./csv"
  delimiter: ","
  interval:
    seconds: 30
  import:
    encoding: ${FILE_ENCODING}
    # for t_articles_group and t_article and t_barcode
    idShop: 9999
    # for t_article and t_barcode
    dtype: 0
    # for t_articles_group
    idParentGroup: 0
    signActivity: true
    # for t_article
    idMaker: 0
    idDepartment: 1
    vatGroup: 1
    saleInTara: false
    active: true
    fiscal: false
    local: true
    printer: 0
    isExcise: 0
    # for t_barcode
    idMeasure: 1
    signFindBarcode: 1