
server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/user/Documents/SimpleExamples/cloud-microservices/config/src/main/resources/config
