#spring.application.name=spring-boot-starter
#
#db.name=postgres123
#db.poolSize=2
#test.msg=hello
#
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
